service: course_imports_api

image: tomosjohnrees/course_imports_api

servers:
  web:
    - 188.245.66.164

proxy:
  ssl: true
  host: courseimports.com

registry:
  server: ghcr.io
  username: tomosjohnrees
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - COURSE_IMPORTS_API_DATABASE_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: course_imports_api-db

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "course_imports_api_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: arm64

accessories:
  db:
    image: postgres:17
    host: 188.245.66.164
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: course_imports_api
        POSTGRES_DB: course_imports_api_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
